// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: envelope.proto

#ifndef PROTOBUF_envelope_2eproto__INCLUDED
#define PROTOBUF_envelope_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_envelope_2eproto();
void protobuf_AssignDesc_envelope_2eproto();
void protobuf_ShutdownFile_envelope_2eproto();

class Envelope;

// ===================================================================

class Envelope : public ::google::protobuf::Message {
 public:
  Envelope();
  virtual ~Envelope();

  Envelope(const Envelope& from);

  inline Envelope& operator=(const Envelope& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Envelope& default_instance();

  void Swap(Envelope* other);

  // implements Message ----------------------------------------------

  Envelope* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Envelope& from);
  void MergeFrom(const Envelope& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 timestamp = 1;
  inline bool has_timestamp() const;
  inline void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  inline ::google::protobuf::int32 timestamp() const;
  inline void set_timestamp(::google::protobuf::int32 value);

  // optional string ticker = 2;
  inline bool has_ticker() const;
  inline void clear_ticker();
  static const int kTickerFieldNumber = 2;
  inline const ::std::string& ticker() const;
  inline void set_ticker(const ::std::string& value);
  inline void set_ticker(const char* value);
  inline void set_ticker(const char* value, size_t size);
  inline ::std::string* mutable_ticker();
  inline ::std::string* release_ticker();
  inline void set_allocated_ticker(::std::string* ticker);

  // @@protoc_insertion_point(class_scope:Envelope)
 private:
  inline void set_has_timestamp();
  inline void clear_has_timestamp();
  inline void set_has_ticker();
  inline void clear_has_ticker();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* ticker_;
  ::google::protobuf::int32 timestamp_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_envelope_2eproto();
  friend void protobuf_AssignDesc_envelope_2eproto();
  friend void protobuf_ShutdownFile_envelope_2eproto();

  void InitAsDefaultInstance();
  static Envelope* default_instance_;
};
// ===================================================================


// ===================================================================

// Envelope

// optional int32 timestamp = 1;
inline bool Envelope::has_timestamp() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Envelope::set_has_timestamp() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Envelope::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Envelope::clear_timestamp() {
  timestamp_ = 0;
  clear_has_timestamp();
}
inline ::google::protobuf::int32 Envelope::timestamp() const {
  return timestamp_;
}
inline void Envelope::set_timestamp(::google::protobuf::int32 value) {
  set_has_timestamp();
  timestamp_ = value;
}

// optional string ticker = 2;
inline bool Envelope::has_ticker() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Envelope::set_has_ticker() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Envelope::clear_has_ticker() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Envelope::clear_ticker() {
  if (ticker_ != &::google::protobuf::internal::kEmptyString) {
    ticker_->clear();
  }
  clear_has_ticker();
}
inline const ::std::string& Envelope::ticker() const {
  return *ticker_;
}
inline void Envelope::set_ticker(const ::std::string& value) {
  set_has_ticker();
  if (ticker_ == &::google::protobuf::internal::kEmptyString) {
    ticker_ = new ::std::string;
  }
  ticker_->assign(value);
}
inline void Envelope::set_ticker(const char* value) {
  set_has_ticker();
  if (ticker_ == &::google::protobuf::internal::kEmptyString) {
    ticker_ = new ::std::string;
  }
  ticker_->assign(value);
}
inline void Envelope::set_ticker(const char* value, size_t size) {
  set_has_ticker();
  if (ticker_ == &::google::protobuf::internal::kEmptyString) {
    ticker_ = new ::std::string;
  }
  ticker_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Envelope::mutable_ticker() {
  set_has_ticker();
  if (ticker_ == &::google::protobuf::internal::kEmptyString) {
    ticker_ = new ::std::string;
  }
  return ticker_;
}
inline ::std::string* Envelope::release_ticker() {
  clear_has_ticker();
  if (ticker_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = ticker_;
    ticker_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Envelope::set_allocated_ticker(::std::string* ticker) {
  if (ticker_ != &::google::protobuf::internal::kEmptyString) {
    delete ticker_;
  }
  if (ticker) {
    set_has_ticker();
    ticker_ = ticker;
  } else {
    clear_has_ticker();
    ticker_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_envelope_2eproto__INCLUDED
